# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildProject: 'src/Tabler/Tabler.csproj'
  buildDemoProject: 'test/Tabler.Test.Wasm/Tabler.Test.Wasm.csproj'
  buildDemoProjectOutput: '$(System.ArtifactsDirectory)'

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: build_tabler
    displayName: 'Build Tabler for Blazor'
    steps:        
    - script: dotnet build $(buildProject) --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildProject)'

  - job: publish_tabler
    displayName: 'Publish Tabler for Blazor'
    steps:        
      - script: dotnet publish $(buildDemoProject) --configuration $(buildConfiguration) --output $(System.ArtifactsDirectory)
        displayName: 'dotnet build $(buildDemoProject)'       

- stage: deploy_demo_site
  displayName: 'Deploy demo site'
  jobs:
    - deployment: demo_deploy
      environment: 'Demo'
      strategy:
        runOnce:
          preDeploy:
            steps:       
              - download: current
                artifact: $(System.ArtifactsDirectory)  

              - task: Npm@1
                displayName: 'Install netlify client'
                inputs:
                  command: 'custom'
                  customCommand: 'install netlify-cli'

          deploy:
            steps:
              - script: npx netlify deploy --dir $(buildDemoProjectOutput)/wwwroot --site $(netlify_site_id) --auth $(netlify_api_key)
                displayName: 'netlify deploy'

