# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildProject: 'src/Tabler/Tabler.csproj'
  buildDemoProject: 'test/Tabler.Test.Wasm/Tabler.Test.Wasm.csproj'
  buildDemoProjectOutput: 'demo-dist'

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: Tabler
    displayName: 'Build Tabler for Blazor'
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.201'
        
    - script: dotnet build $(buildProject) --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildProject)'

- stage: deploy_demo_site
  displayName: 'Deploy demo site'
  jobs:
    - deployment: 
      strategy:
        runOnce:
          preDeploy:
            steps:
              - script: dotnet publish $(buildDemoProject) --configuration $(buildConfiguration) --output $(buildDemoProjectOutput)
                displayName: 'dotnet build $(buildDemoProject)'                
              - task: Npm@1
                displayName: 'Install netlify client'
                inputs:
                  command: 'custom'
                  customCommand: 'install netlify-cli'

          deploy:
            steps:
              - script: npx netlify deploy --dir $(buildDemoProjectOutput)/wwwroot --site $(netlify_site_id) --auth $(netlify_api_key)
                displayName: 'netlify deploy'

