# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 'Table.Blazor-build.$(Rev:.r)'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildProject: 'src/Tabler/Tabler.csproj'
  buildDemoProject: 'test/Tabler.Test.Wasm/Tabler.Test.Wasm.csproj'

jobs:
- job: build_tabler
  displayName: 'Build Tabler for Blazor'
  steps:        
  - script: dotnet build $(buildProject) --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildProject)'

  - script: dotnet build $(buildDemoProject) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
    displayName: 'dotnet build $(buildDemoProject)'
