# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildProject: 'src/Tabler/Tabler.csproj'
  buildDemoProject: 'test/Tabler.Test.Wasm/Tabler.Test.Wasm.csproj'

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: build_tabler
    displayName: 'Build Tabler for Blazor'
    steps:        
    - script: dotnet build $(buildProject) --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildProject)'

  - job: publish_tabler
    displayName: 'Publish Tabler for Blazor'
    steps:        
      - script: dotnet publish $(buildDemoProject) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
        displayName: 'dotnet build $(buildDemoProject)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'demo_drop'
          publishLocation: 'Container'

- stage: deploy_demo_site
  displayName: 'Deploy demo site'
  jobs:
    - deployment: demo_deploy
      displayName: 'Deploy demo site'
      environment: 'Demo'
      strategy:
        runOnce:
          preDeploy:
            steps:
              - task: Npm@1
                displayName: 'Install netlify client'
                inputs:
                  command: 'custom'
                  customCommand: 'install netlify-cli'

          deploy:
            steps:
              - script: npx netlify deploy --dir $(Build.ArtifactStagingDirectory)/demo_drop/wwwroot --site $(netlify_site_id) --auth $(netlify_api_key)
                displayName: 'netlify deploy'

