# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildProject: 'src/Tabler/Tabler.csproj'
  buildDemoProject: 'test/Tabler.Test.Wasm/Tabler.Test.Wasm.csproj'

jobs:
- job: build_tabler
  displayName: 'Build Tabler for Blazor'
  steps:        
  - script: dotnet build $(buildProject) --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildProject)'

- job: pack_tabler
  displayName: 'Build Tabler for Blazor'
  steps:        
  - script: dotnet pack $(buildProject) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/pack
    displayName: 'dotnet build $(buildProject)'
              
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/pack'
      ArtifactName: 'pack_drop'
      publishLocation: 'Container'

- job: publish_tabler
  displayName: 'Publish Wasm Demo Site'
  steps:        
    - script: dotnet publish $(buildDemoProject) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
      displayName: 'dotnet build $(buildDemoProject)'
              
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
        ArtifactName: 'demo_drop'
        publishLocation: 'Container'
