# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildProject: 'src/Tabler/Tabler.csproj'
  buildDemoProject: 'test/Tabler.Test.Wasm/Tabler.Test.Wasm.csproj'
  buildDemoProjectOutput: 'demo-dist'

jobs:
  - job: Tabler
    displayName: 'Build Tabler for Blazor'
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.201'
        
    - script: dotnet build $(buildProject) --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildProject)'

  - job: DemoSite
    displayName: 'Build demo site'
    steps:
    - task: UseDotNet@2      
      inputs:
        version: '3.1.201'

    - script: dotnet build $(buildDemoProject) --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildDemoProject)'

    - task: Npm@1
      displayName: 'Install netlify client'
      inputs:
        command: 'custom'
        customCommand: 'install netlify-cli'

    - script: npx netlify deploy --dir $(buildDemoProjectOutput) --site $(netlify_site_id) --auth $(netlify_api_key)
      displayName: 'netlify deploy'