# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
  deploy:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        
      - uses: actions/checkout@v1
      - name: Pack package
        run: dotnet pack src\Tabler.csproj --configuration Release
      
      - name: Push package
        run: |
          nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/Tabler.Blazor/index.json -Username ${{ secrets.NugetUser }} -Password ${{ secrets.NugetApiKey }}
          nuget push **\*.nupkg -source "GPR"
